### ISSUE TITLE
Module version expected : 6.0

### ISSUE THREAD

**Issue by urbanovich** [PrestaShopCorp/prestashop-accounts-installer#11]
Hi!

I have tried using prestashop-accounts-installer to install ps_accounts in PS 8.0.0 and see the issue:

```Module version expected : 6.0```

if I use 5.0 version installer send message:

```cURL error 6: Could not resolve host: v1 (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for v1/customers/```

Prestashop accounts installer works with PS 8.0.0 or not ? because I see in the documentation that it should

ps_account version | Prestashop Version | PHP Version | Event Bus installation
6.x                           | >=8.0.0                    | ≥7.2 \|\| ≤8.1  | Yes

**Comment by emmanuelgautier** [comment]
Hi @urbanovich,

The prestashop-accounts-installer works with Prestashop versions from 1.6.1 to 8.x according to this [compatibility matrix](https://github.com/PrestaShopCorp/prestashop-accounts-installer#compatibility-matrix). If you have this message is because the current version of the module installed is 5.x and the version 6.x. . Could you check which version of ps_account is installed on your shop ?

**Comment by urbanovich** [comment]
I use the function:

```php
$this->getService('ps_accounts.installer')->install();
```
for install ps_accounts module but see the response:

```
Could not perform action install for module undefined
```

ps_accounts is not installed at shop but if try to do it in PS 1.7.8.8 the module is installed and I can see it in modules dir

**Comment by emmanuelgautier** [comment]
You do it fine for the code snippet.

As you may know, PS from version 8 does not have a built-in module manager downloading modules from the Addons Marketplace. Have you try to install first with the module [ps_mbo](https://addons.prestashop.com/en/administrative-tools/39574-prestashop-marketplace-in-your-back-office.html) ?

**Comment by urbanovich** [comment]
Thanks @emmanuelgautier !

It works, after installing ps_mbo, execution:

```php
$this->getService('ps_accounts.installer')->install();
```
installed ps_accounts
