### ISSUE TITLE
[ps_accounts] Wrong condition

### ISSUE THREAD

**Issue by d0niek** [PrestaShopCorp/prestashop-accounts-installer#12]
Hi!

It looks like you have wrong conditions in file `ps_accounts.php`, on line `528`.

It looks:

```php
if (!$response || true !== $response['status']) {
```

and I think it should looks like:

```php
if ($response && true !== $response['status']) {
```

My installed version is **5.3.4**.

**Comment by emmanuelgautier** [comment]
Hi @d0niek,

The first condition looks good. The line condition catches two potential errors which are no response object or a response status with an error. Your proposition won't catch the case when there is no response object.

Do you encounter a specific issue with this line?

**Comment by emmanuelgautier** [comment]
I @d0niek,

A new ps_accounts version `5.3.5` has been published today. This new version should be available for download in the coming hours.

Do not hesitate to get back to us if you have the opportunity to test this new version.

Thanks again for raising this issue and contributing to improving Prestashop modules.

**Comment by d0niek** [comment]
Hi @emmanuelgautier !

Code looks like:

```php
if (!$response || true !== $response['status']) {
    $this->getLogger()->debug(
        'Error trying to PATCH shop : ' . $response['httpCode'] .
        ' ' . print_r($response['body']['message'], true)
    );
}
```

I think you can't check if `$response is empty` and then use `$response['some_key']`. For sure `'some_key'` doesn't exists, `$response is empty` (!).

I thought that condition is wrong but you said that you want to catch `empty $response`. If so you have to log different message for that, without using this object in the log message.

**Comment by emmanuelgautier** [comment]
A fix for this issue has been released. This issue can be closed. Thanks for having created this issue.
