### ISSUE TITLE
how to change account?

### ISSUE THREAD

**Issue by blawdi** [PrestaShopCorp/prestashop-accounts-installer#13]
Hello, how to change account ?

**Comment by emmanuelgautier** [comment]
Hello @blawdi,

This repository manages `ps_accounts` technical Prestashop module. You may be on the wrong communication channel. You should have a look at [Prestashop Help Center](https://help-center.prestashop.com/).

**Comment by blawdi** [comment]
Hello, I'm not used to Github, but my problem is PS_accounts.
I bought a Prestashop and I can't change the account of Ps_accounts which is still on the old owner, I have tried to delete and reinitialize the module and all the other linked 'event bus' but nothing works. Where should I ask / report the problem I'm having?

**Comment by emmanuelgautier** [comment]
GitHub issues section is more for technical questions and implementation suggestions than support. You should have a look first at the [Prestashop Help Center](https://help-center.prestashop.com/). If you do not find an answer, do not hesitate to reach the support team, they will be able to help you.

ps_accounts associates a shop with an owner and only this owner can dissociate his shop. If you still can reach the formal shop owner, you should ask him to dissociate his shop. He can dissociate his shop on the ps_account modal in his shop list on your shop Back Office or any other ps_accounts installed on other Prestashop shop.

Hope this explanation can give you a first answer. I close this issue and let you reach the support team if it is not.
