### ISSUE TITLE
can't associate ps_accounts

### ISSUE THREAD

**Issue by iamluxan** [PrestaShopCorp/prestashop-accounts-installer#17]
Hello.

I am trying to configure ps_Accounts & ps_checkout, I downloaded and installed ps_accounts, but when I try to configure the account module, and associate my store with my prestashop account, it fails to make the association and therefore I can't configure prestashop checkout module.

I work on a local environnement (local.xxx.com)

![Capture d’écran 2023-09-15 à 07 52 20](https://github.com/PrestaShopCorp/prestashop-accounts-installer/assets/1712625/0275e647-2a09-4b93-8e5c-23e541a3e56c)

Any help you be greatly apreciated.

regards

**Comment by antoinemetifeu** [comment]
Hello @luxanletexan, to be associated with PS Accounts, our shop should be accessible from internet

**Comment by iamluxan** [comment]
Bonjour Antoine,
Vous voulez dire que je ne peux pas tester en local le module ps_checkout qui nécessite l’association de ps_accounts pour son utilisation ?
Il faut obligatoirement tester en live ? Nous devions installer et customiser de module avant de passer en production.
Merci

**Comment by antoinemetifeu** [comment]
Si vous pouvez rendre votre environnement local accessible depuis internet le temps de l'association, cela devrait fonctionner.

En cas de question ou d'autres demandes d'aide, je vous invite à nous contacter via le centre d'aide https://help-center.prestashop.com/fr
